M48
; DRILL file {KiCad 7.0.1-0} date 2023 September 27, Wednesday 15:06:46
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-27T15:06:46-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.1-0
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0394
%
G90
G05
T1
X-0.0709Y-0.0236
T2
X-0.0994Y0.1969
X0.0006Y0.1969
X0.1006Y0.1969
T0
M30
