M48
; DRILL file {KiCad 7.0.2-0} date 2023 May 22, Monday 20:56:37
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-05-22T20:56:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.2-0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0630
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X1.1004Y-1.7486
X1.3366Y-1.5124
T2
X0.9Y-3.65
X2.5Y-3.65
X2.6Y-1.9
X2.6Y-3.1
X4.1Y-1.9
X4.1Y-3.1
X4.5Y-1.98
X4.5Y-3.02
T0
M30
